relay:
  host: 57.128.188.155
  port: 4953
  connection:
    retries: 3
    retryDelay: 5000
  user:
    name: Chloe
    id: daai56a8
osc:
  local:
    sendPort: 9000
    receivePort: 9001
    queryPort: 9012
    ip: 127.0.0.1
filters:
  blacklist:
    console:
      - /avatar/parameters/VelocityX
      - /avatar/parameters/VelocityY
      - /avatar/parameters/VelocityZ
      - /avatar/parameters/InStation
    transmission:
      - /avatar/parameters/Voice
      - /monitoring/.*
      - /avatar/parameters/VFH/.*
logging:
  console: true
  file: true
  osc:
    incoming: true
    outgoing: true
  path: logs/client
