relay:
  host: "57.128.188.155"
  port: 4953
  maxRetries: 5

osc:
  local:
    sendPort: 9000
    receivePort: 9001
    queryPort: 9012
    ip: "127.0.0.1"

filters:
  blacklist:
    - /avatar/parameters/VelocityX
    - /avatar/parameters/VelocityY
    - /avatar/parameters/VelocityZ
    - /avatar/parameters/InStation
    - /monitoring/.*
    - /avatar/parameters/VF54_SyncDataNum
    - /avatar/parameters/VF54_SyncPointer
    - /avatar/parameters/Voice
    - /avatar/parameters/VFH/.*
    - /avatar/parameters/0_Angle
    - /avatar/parameters/VF70_TC_current_trackingEyes
    - /avatar/parameters/VF70_TC_current_trackingRightFoot
    - /avatar/parameters/VF70_TC_current_trackingLeftFoot
    - /avatar/parameters/VF70_TC_current_trackingMouth
    - /avatar/parameters/VF70_TC_current_trackingRightFingers
    - /avatar/parameters/VF70_TC_current_trackingLeftFingers
    - /avatar/parameters/VF70_TC_current_trackingHip
    - /avatar/parameters/VF70_TC_current_trackingRightHand
    - /avatar/parameters/VF70_TC_current_trackingLeftHand
    - /avatar/parameters/VF70_TC_current_trackingHead
    - /avatar/parameters/VF70_TC_FullControllerBuilder.Apply_on_GogoLoco_Beyond_(VRCFury)_trackingRightFoot
    - /avatar/parameters/VF70_TC_FullControllerBuilder.Apply_on_GogoLoco_Beyond_(VRCFury)_trackingLeftFoot
    - /avatar/parameters/Go/Crouch
    - /avatar/parameters/Go/Mirror
    - /avatar/parameters/VelocityMagnitude
    - /avatar/parameters/AngularY
    - /avatar/parameters/Go/Jump
    - /avatar/parameters/Grounded