relay:
  host: 57.128.188.155
  port: 4953
  maxRetries: 5
  connection:
    retries: 3 // -1 for endless
    retryDelay: 5000  
  user:
    name: Chloe
    id: 15000
osc:
  local:
    sendPort: 9000
    receivePort: 9001
    queryPort: 9012
    ip: 127.0.0.1
filters:
  blacklist:
    console:  # Messages that won't be logged but will be transmitted
      - /avatar/parameters/VelocityX
      - /avatar/parameters/VelocityY
      - /avatar/parameters/VelocityZ
      - /avatar/parameters/InStation
      - /avatar/parameters/0_Angle
      - /avatar/parameters/VF70_TC_current_trackingEyes
      - /avatar/parameters/VF70_TC_current_trackingRightFoot
      - /avatar/parameters/VF70_TC_current_trackingLeftFoot
      - /avatar/parameters/VF70_TC_current_trackingMouth
      - /avatar/parameters/VF70_TC_current_trackingRightFingers
      - /avatar/parameters/VF70_TC_current_trackingLeftFingers
      - /avatar/parameters/VF70_TC_current_trackingHip
      - /avatar/parameters/VF70_TC_current_trackingRightHand
      - /avatar/parameters/VF70_TC_current_trackingLeftHand
      - /avatar/parameters/VF70_TC_current_trackingHead
      - /avatar/parameters/VF70_TC_FullControllerBuilder.Apply_on_GogoLoco_Beyond_(VRCFury)_trackingRightFoot
      - /avatar/parameters/VF70_TC_FullControllerBuilder.Apply_on_GogoLoco_Beyond_(VRCFury)_trackingLeftFoot
      - /avatar/parameters/Go/Crouch
      - /avatar/parameters/Go/Mirror
      - /avatar/parameters/VelocityMagnitude
      - /avatar/parameters/AngularY
      - /avatar/parameters/Go/Jump
      - /avatar/parameters/Grounded
    transmission:  # Messages that won't be transmitted at all
      - /avatar/parameters/Voice
      - /monitoring/.*
      - /avatar/parameters/VFH/.*
      - /avatar/parameters/VF54_SyncDataNum
      - /avatar/parameters/VF54_SyncPointer
      - /avatar/parameters/VelocityX
      - /avatar/parameters/VelocityY
      - /avatar/parameters/VelocityZ
      - /avatar/parameters/InStation
      - /avatar/parameters/0_Angle
      - /avatar/parameters/VF70_TC_current_trackingEyes
      - /avatar/parameters/VF70_TC_current_trackingRightFoot
      - /avatar/parameters/VF70_TC_current_trackingLeftFoot
      - /avatar/parameters/VF70_TC_current_trackingMouth
      - /avatar/parameters/VF70_TC_current_trackingRightFingers
      - /avatar/parameters/VF70_TC_current_trackingLeftFingers
      - /avatar/parameters/VF70_TC_current_trackingHip
      - /avatar/parameters/VF70_TC_current_trackingRightHand
      - /avatar/parameters/VF70_TC_current_trackingLeftHand
      - /avatar/parameters/VF70_TC_current_trackingHead
      - /avatar/parameters/VF70_TC_FullControllerBuilder.Apply_on_GogoLoco_Beyond_(VRCFury)_trackingRightFoot
      - /avatar/parameters/VF70_TC_FullControllerBuilder.Apply_on_GogoLoco_Beyond_(VRCFury)_trackingLeftFoot
      - /avatar/parameters/Go/Crouch
      - /avatar/parameters/Go/Mirror
      - /avatar/parameters/VelocityMagnitude
      - /avatar/parameters/AngularY
      - /avatar/parameters/Go/Jump
      - /avatar/parameters/Grounded
logging:
  console: true
  file: true
  osc:
    incoming: true
    outgoing: true
